run: 14
b:
	g++ Main.cpp && cat input | ./a.out
14:
	g++ -std=c++14 main.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG -lncurses
	./a.out
11:
	g++ -std=c++11 main.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG
	./a.out 
