run: 17
b:
	g++ Main.cpp && cat input | ./a.out
17:
	g++ -std=c++17 Main.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG -lncurses
	./a.out
14:
	g++ -std=c++14 Main.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG -lncurses
	./a.out
11:
	g++ -std=c++11 Main.cpp -Wall -g -fsanitize=undefined -D_GLIBCXX_DEBUG
	./a.out 
