[[plugins]]
repo = 'sheerun/vim-polyglot'

#[[plugins]]
#repo = 'Shougo/neco-syntax'

#[[plugins]]
#repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'anoike/vim-moneyforward'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'Shougo/denite.nvim'
#hook_add = '''
#  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
#  call denite#custom#var('grep', 'command', ['ag'])
#  call denite#custom#var('grep', 'recursive_opts', [])
#  call denite#custom#var('grep', 'pattern_opt', [])
#  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
#
#  nnoremap <silent>sf :Denite file_rec<CR>
#  nnoremap <silent>sg :Denite grep -mode=normal<CR>
#  nnoremap <silent>sy :Denite neoyank -mode=normal<CR>
#  nnoremap <silent>sb :Denite buffer -mode=normal<CR>
#	nnoremap <silent>t :DeniteCursorWord -buffer-name=gtags_def gtags_def -mode=normal<CR>
#'''
#
#[[plugins]]
#repo = 'Shougo/Vinarise'

#[[plugins]]
#repo = 'ozelentok/denite-gtags'

#[[plugins]]
#repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'cohama/lexima.vim'

#[[plugins]]
#repo = 'majutsushi/tagbar'
#hook_add = '''
#nmap <C-l> :TagbarToggle<CR>
#'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1
